CFLAGS += $(shell xeno-config --skin=native --cflags)
LDFLAGS += $(shell xeno-config --skin=native --ldflags)
LDFLAGS += -lrtdk

all: edfomai.o

edfomai: edfomai.o
	$(CC) edfomai.o $(LDFLAGS) -o edfomai
edfomai.o: edfomai.c
	$(CC) -c $(CFLAGS) edfomai.c

clean:
	rm -f edfomai.o edfomai

