CFLAGS += $(shell xeno-config --skin=native --cflags)
LDFLAGS += $(shell xeno-config --skin=native --ldflags)
LDFLAGS += -lrtdk
LDFLAGS += -lrtdm

all : edfomai-app.o single_test

single_test : edfomai-app.o single_test.o
	$(CC) single_test.o edfomai-app.o $(LDFLAGS) -o single_test

single_test.o : single_test.c
	$(CC) -c $(CFLAGS) single_test.c

edfomai-app.o : edfomai-app.c
	$(CC) -c $(CFLAGS) edfomai-app.c

clean :
	rm -f edfomai-app.o single_test.o single_test

